import type { Employee } from './types';

export const INITIAL_EMPLOYEES: Employee[] = [
    {
        id: 'emp1',
        sN: 1,
        gumboot: '43',
        uniform: 'L',
        jacket: 'L',
        cost: '150',
        compNo: 'C-123',
        sapNo: 'S-456',
        name: 'Mohammed Ali',
        designation: 'Farm Leadman',
        sponsor: 'Al Watania Poultry',
        grade: 'A',
        nationality: 'Saudi Arabian',
        joiningDate: '2020-01-15',
        farmNo: 'B2/3',
        area: 'Butain 2',
        iqamaNo: '2458796541',
        iqamaExpiry: '2025-06-20',
        passportNo: 'P12345678',
        passportExpiry: '2028-11-10',
        religion: 'Islam',
        mobileNo: '0501234567',
    },
    {
        id: 'emp2',
        sN: 2,
        gumboot: '44',
        uniform: 'M',
        jacket: 'M',
        cost: '250',
        compNo: 'C-124',
        sapNo: 'S-457',
        name: 'John Smith',
        designation: 'Farm Worker',
        sponsor: 'Al Watania Poultry',
        grade: 'B',
        nationality: 'American',
        joiningDate: '2018-05-22',
        farmNo: 'She/1',
        area: 'Shemalia',
        iqamaNo: '2369854712',
        iqamaExpiry: '2024-12-31',
        passportNo: 'A98765432',
        passportExpiry: '2027-02-15',
        religion: 'Christianity',
        mobileNo: '0519876543',
    },
     {
        id: 'emp3',
        sN: 3,
        gumboot: '41',
        uniform: 'S',
        jacket: 'S',
        cost: '100',
        compNo: 'C-125',
        sapNo: 'S-458',
        name: 'Rajesh Kumar',
        designation: 'Farm Worker',
        sponsor: 'Al Watania Poultry',
        grade: 'C',
        nationality: 'Indian',
        joiningDate: '2022-09-01',
        farmNo: 'B3/1',
        area: 'Butain 3',
        iqamaNo: '2541236987',
        iqamaExpiry: '2026-03-14',
        passportNo: 'N56473829',
        passportExpiry: '2030-08-01',
        religion: 'Hinduism',
        mobileNo: '0537485960',
    },
    // Adding more employees for report data
    {
        id: 'emp4',
        sN: 4,
        gumboot: '42',
        uniform: 'L',
        jacket: 'L',
        cost: '',
        compNo: 'C-126',
        sapNo: 'S-459',
        name: 'Ahmed Hassan',
        designation: 'Acting Leadman',
        sponsor: 'Al Watania Poultry',
        grade: 'A',
        nationality: 'Egyptian',
        joiningDate: '2021-03-10',
        farmNo: 'B2/4',
        area: 'Butain 2',
        iqamaNo: '2987654321',
        iqamaExpiry: '2025-01-01',
        passportNo: 'E12345678',
        passportExpiry: '2029-01-01',
        religion: 'Islam',
        mobileNo: '0551234567',
    },
    {
        id: 'emp5',
        sN: 5,
        gumboot: '43',
        uniform: 'M',
        jacket: 'M',
        cost: '',
        compNo: 'C-127',
        sapNo: 'S-460',
        name: 'Yusuf Ibrahim',
        designation: 'Farm Night Man',
        sponsor: 'Al Watania Poultry',
        grade: 'B',
        nationality: 'Pakistani',
        joiningDate: '2019-11-05',
        farmNo: 'B2/3',
        area: 'Butain 2',
        iqamaNo: '2123456789',
        iqamaExpiry: '2024-10-10',
        passportNo: 'F87654321',
        passportExpiry: '2026-05-20',
        religion: 'Islam',
        mobileNo: '0555555555',
    },
    {
        id: 'emp6',
        sN: 6,
        gumboot: '44',
        uniform: 'XL',
        jacket: 'XL',
        cost: '',
        compNo: 'C-128',
        sapNo: 'S-461',
        name: 'Farid Khan',
        designation: 'Farm Worker',
        sponsor: 'Al Watania Poultry',
        grade: 'C',
        nationality: 'Bangladeshi',
        joiningDate: '2021-08-19',
        farmNo: 'B2/3',
        area: 'Butain 2',
        iqamaNo: '2987123456',
        iqamaExpiry: '2025-09-11',
        passportNo: 'G54321987',
        passportExpiry: '2029-04-03',
        religion: 'Islam',
        mobileNo: '0541239876',
    },
    { id: 'emp7', sN: 7, gumboot: '42', uniform: 'L', jacket: '', cost: '', compNo: 'C-129', sapNo: 'S-462', name: 'Employee A', designation: 'Farm Worker', sponsor: '', grade: '', nationality: '', joiningDate: '2021-01-01', farmNo: 'B2/3', area: 'Butain 2', iqamaNo: '', iqamaExpiry: '', passportNo: '', passportExpiry: '', religion: '', mobileNo: '' },
    { id: 'emp8', sN: 8, gumboot: '43', uniform: 'L', jacket: '', cost: '', compNo: 'C-130', sapNo: 'S-463', name: 'Employee B', designation: 'Farm Worker', sponsor: '', grade: '', nationality: '', joiningDate: '2021-01-01', farmNo: 'B2/3', area: 'Butain 2', iqamaNo: '', iqamaExpiry: '', passportNo: '', passportExpiry: '', religion: '', mobileNo: '' },
    { id: 'emp9', sN: 9, gumboot: '43', uniform: 'M', jacket: 'M', cost: '', compNo: 'C-131', sapNo: 'S-464', name: 'Employee C', designation: 'Farm Leadman', sponsor: '', grade: '', nationality: '', joiningDate: '2020-01-01', farmNo: 'B2/4', area: 'Butain 2', iqamaNo: '', iqamaExpiry: '', passportNo: '', passportExpiry: '', religion: '', mobileNo: '' },
    { id: 'emp10', sN: 10, gumboot: '44', uniform: 'M', jacket: '', cost: '', compNo: 'C-132', sapNo: 'S-465', name: 'Employee D', designation: 'Farm Night Man', sponsor: '', grade: '', nationality: '', joiningDate: '2020-01-01', farmNo: 'B2/4', area: 'Butain 2', iqamaNo: '', iqamaExpiry: '', passportNo: '', passportExpiry: '', religion: '', mobileNo: '' },
    { id: 'emp11', sN: 11, gumboot: '42', uniform: 'L', jacket: '', cost: '', compNo: 'C-133', sapNo: 'S-466', name: 'Employee E', designation: 'Acting Nightman', sponsor: '', grade: '', nationality: '', joiningDate: '2022-01-01', farmNo: 'B2/4', area: 'Butain 2', iqamaNo: '', iqamaExpiry: '', passportNo: '', passportExpiry: '', religion: '', mobileNo: '' },
    { id: 'emp12', sN: 12, gumboot: '43', uniform: 'S', jacket: '', cost: '', compNo: 'C-134', sapNo: 'S-467', name: 'Employee F', designation: 'Farm Worker', sponsor: '', grade: '', nationality: '', joiningDate: '2022-01-01', farmNo: 'B2/2', area: 'Butain 2', iqamaNo: '', iqamaExpiry: '', passportNo: '', passportExpiry: '', religion: '', mobileNo: '' },
    { id: 'emp13', sN: 13, gumboot: '41', uniform: 'S', jacket: '', cost: '', compNo: 'C-135', sapNo: 'S-468', name: 'Employee G', designation: 'Farm Worker', sponsor: '', grade: '', nationality: '', joiningDate: '2022-01-01', farmNo: 'B2/2', area: 'Butain 2', iqamaNo: '', iqamaExpiry: '', passportNo: '', passportExpiry: '', religion: '', mobileNo: '' },
    { id: 'emp14', sN: 14, gumboot: '45', uniform: 'XL', jacket: '', cost: '', compNo: 'C-136', sapNo: 'S-469', name: 'Employee H', designation: 'Farm Leadman', sponsor: '', grade: '', nationality: '', joiningDate: '2019-01-01', farmNo: 'B2/2', area: 'Butain 2', iqamaNo: '', iqamaExpiry: '', passportNo: '', passportExpiry: '', religion: '', mobileNo: '' },
    { id: 'emp15', sN: 15, gumboot: '44', uniform: 'XL', jacket: '', cost: '', compNo: 'C-137', sapNo: 'S-470', name: 'Employee I', designation: 'Acting Nightman', sponsor: '', grade: '', nationality: '', joiningDate: '2023-01-01', farmNo: 'B2/2', area: 'Butain 2', iqamaNo: '', iqamaExpiry: '', passportNo: '', passportExpiry: '', religion: '', mobileNo: '' },
    { id: 'emp16', sN: 16, gumboot: '44', uniform: 'XL', jacket: '', cost: '', compNo: 'C-138', sapNo: 'S-471', name: 'Employee J', designation: 'Farm Leadman', sponsor: '', grade: '', nationality: '', joiningDate: '2023-01-01', farmNo: 'B3/3', area: 'Butain 3', iqamaNo: '', iqamaExpiry: '', passportNo: '', passportExpiry: '', religion: '', mobileNo: '' },
    { id: 'emp17', sN: 17, gumboot: '44', uniform: 'L', jacket: 'L', cost: '', compNo: 'C-139', sapNo: 'S-472', name: 'Employee K', designation: 'Acting Nightman', sponsor: '', grade: '', nationality: '', joiningDate: '2023-01-01', farmNo: 'B3/3', area: 'Butain 3', iqamaNo: '', iqamaExpiry: '', passportNo: '', passportExpiry: '', religion: '', mobileNo: '' },
    { id: 'emp18', sN: 18, gumboot: '43', uniform: 'L', jacket: '', cost: '', compNo: 'C-140', sapNo: 'S-473', name: 'Employee L', designation: 'Farm Worker', sponsor: '', grade: '', nationality: '', joiningDate: '2023-01-01', farmNo: 'B3/3', area: 'Butain 3', iqamaNo: '', iqamaExpiry: '', passportNo: '', passportExpiry: '', religion: '', mobileNo: '' },
    { id: 'emp19', sN: 19, gumboot: '42', uniform: 'M', jacket: '', cost: '', compNo: 'C-141', sapNo: 'S-474', name: 'Employee M', designation: 'Farm Worker', sponsor: '', grade: '', nationality: '', joiningDate: '2023-01-01', farmNo: 'B3/3', area: 'Butain 3', iqamaNo: '', iqamaExpiry: '', passportNo: '', passportExpiry: '', religion: '', mobileNo: '' },
    { id: 'emp20', sN: 20, gumboot: '42', uniform: 'M', jacket: '', cost: '', compNo: 'C-142', sapNo: 'S-475', name: 'Employee N', designation: 'Farm Worker', sponsor: '', grade: '', nationality: '', joiningDate: '2023-01-01', farmNo: 'B3/3', area: 'Butain 3', iqamaNo: '', iqamaExpiry: '', passportNo: '', passportExpiry: '', religion: '', mobileNo: '' },
    { id: 'emp21', sN: 21, gumboot: '41', uniform: 'S', jacket: '', cost: '', compNo: 'C-143', sapNo: 'S-476', name: 'Employee O', designation: 'Farm Worker', sponsor: '', grade: '', nationality: '', joiningDate: '2023-01-01', farmNo: 'B3/3', area: 'Butain 3', iqamaNo: '', iqamaExpiry: '', passportNo: '', passportExpiry: '', religion: '', mobileNo: '' },
];
